Modified to reflect reality
Daggy1234/dagpi pull request #1
Opened 2020-06-22 23:53 UTC by ir-3

Number 1 Discord Bot -> Number 4,137th Discord Bot
FastAPI -> SlowAPI
quickly manipulate -> slowly manipulate

2020-06-22 23:56 UTC, Zomatree requested changes
Discord should be capitalized.

2020-06-23 00:05 UTC, ir-3 commented
Okay, I have edited it to add brevity and fix the issues of flow and capitalization. It now reads as follows...

`Welcome to DAGPI, the API for the 4,137th ranked Discord meme bot. DAGPI was built on SlowAPI and provides image manipulation via ImageMagick and Pillow to slowly and barely manipulate both GIFs and images.`

2020-06-23 00:08 UTC, Equity commented
LGTM!

2020-06-23 00:10 UTC, linKhehe reviewed
I agree with this; however, I have also added more changes that I think will make for a more interesting and gratifying read. Thanks, Zoma.

2020-06-23 00:12 UTC, ir-3 commented
I think this should be good to go now, we just need @Daggy1234's approval then we can get to rolling this out the the ~~thousands~~ hundreds of thousands of DAGPI users. Also, can I just add this here since this is a large forum of DAGAPI diehards? The name DAGPI just really rolls off of the tongue. I am a big fan and honestly, I can't imagine the name improving with an extra character, even an "a", or different capitalization. Great creative work on this team.

2020-06-23 05:15 UTC, Daggy1234 commented
Ummm wack but like no thanks

2020-06-23 05:15 UTC, closed without merging

2020-06-23 05:18 UTC, ir-3 commented
Even though I feel as if you have made a miscalculation with this decision, I will still respect it. If you are closing this, you should close #2

2020-06-23 12:11 UTC, crrapi commented
I believe this should be merged, as you should always be transparent with your users

2020-06-23 12:12 UTC, crrapi commented
@Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Daggy1234 @Da [...]

2020-06-23 12:12 UTC, Daggy1234 commented
@crrapi Hello look at in the  statement I used. in the issued.